### ISSUE TITLE
Initial commit & readme

### ISSUE THREAD

**Issue by alce65** [MiguelGarcia98GitHub/202210-W3CH5-Miguel-Garcia#2]
Hola Miguel.
El commit inicial no debe incluir un readme sin sentido.
Tiene que incluir UN CONTENIDO VÁLIDO: al menos las instrucciones para hacer el challenge.
Esto YA lo deberías tener desde el principio.

**Comment by MiguelGarcia98GitHub** [comment]
Corregido el readme, gracias.

**Comment by alce65** [comment]
De nada. Bien hecho, cierro el issue
